// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJvSHUFNtTlFNyw_5AQPH4b-x_f8LadbM',
    appId: '1:1022011611607:android:0b28539add5365d103d392',
    messagingSenderId: '1022011611607',
    projectId: 'firepool-18172',
    storageBucket: 'firepool-18172.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_MCxA4Mq7t8hVUaJIuj8Xm5VZfgIwyGw',
    appId: '1:1022011611607:ios:c589f7325deea59203d392',
    messagingSenderId: '1022011611607',
    projectId: 'firepool-18172',
    storageBucket: 'firepool-18172.appspot.com',
    androidClientId: '1022011611607-plul61095cgcpqpqdrtaees93tetiual.apps.googleusercontent.com',
    iosClientId: '1022011611607-5saacoavds6lsa1k2ft7jsfbeu3q27b7.apps.googleusercontent.com',
    iosBundleId: 'com.example.arInteriorVisualizer',
  );

}